### ISSUE TITLE
`mb_convert_encoding` does not support `windows-1250`.

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#1037]
### Expected behavior
The app should be able to read popular encodings.

### Actual behavior
Some encodings (e.g. `windows-1250` and Arabic) cause warnings/errors. Apparently that's not supported by the build-in function: https://secure.php.net/manual/de/mbstring.supported-encodings.php. However, some clients (Outlook, I suppose) use this encoding.

### Mail app

**Mail app version:**
0.9.0

### Server configuration

**PHP version:**
7.0

**Nextcloud Version:**
14 Beta 4

Ref https://sentry.io/share/issue/303496811cbc42899c531fbe51a3e37f/.

**Comment by whirm** [comment]
I'm not seeing .ics files attached to e-mails (works just fine with other webmails) and this error shows every time I load an e-mail:

```
mb_convert_encoding(): Illegal character encoding specified at /var/www/html/custom_apps/mail/lib/Model/IMAPMessage.php#553
```

I'm guessing it's the same issue? 

I'm running 16.0.1 and Mail 0.15.1 on PHP 7.3.6

**Comment by ChristophWurst** [comment]
> I'm guessing it's the same issue?

would you be able to attach debugger or add some logs to verify?

**Comment by HLFH** [comment]
For windows-1256 / cp1256 support, could be interesting to look into this code: https://github.com/khaled-alshamaa/ar-php/blob/master/src/Arabic.php

At the section * Convert Arabic string into glyph joining in UTF-8 hexadecimals stream*.

**Comment by HLFH** [comment]
ìconv` does not support the following 27 charsets:

> UTF7-IMAP
ISO-2022-JP-MS
CP51932
SJIS-mac (alias: MacJapanese)
SJIS-Mobile#DOCOMO (alias: SJIS-DOCOMO)
SJIS-Mobile#KDDI (alias: SJIS-KDDI)
SJIS-Mobile#SOFTBANK (alias: SJIS-SOFTBANK)
UTF-8-Mobile#DOCOMO (alias: UTF-8-DOCOMO)
UTF-8-Mobile#KDDI-A
UTF-8-Mobile#KDDI-B (alias: UTF-8-KDDI)
UTF-8-Mobile#SOFTBANK (alias: UTF-8-SOFTBANK)
ISO-2022-JP-MOBILE#KDDI (alias: ISO-2022-JP-KDDI)
JIS
JIS-ms
CP50220
CP50220raw
CP50221
CP50222
byte2be
byte2le
byte4be
byte4le
BASE64
HTML-ENTITIES (alias: HTML)
7bit
8bit
HZ

But ìconv` supports windows-1250 and windows-1256...

**Comment by HLFH** [comment]
This issue is fully fixed by the PR https://github.com/nextcloud/mail/pull/5593.

**Comment by adarnimrod** [comment]
I think that #5834, #5845, #5998 are duplicate issues and that PR #5882 addresses the same.
My issue has been that I stopped seeing new messages. Clearing the cache made it so I didn't see any messages. The error was `PHP Fatal error:  Uncaught ValueError: mb_convert_encoding(): Argument #3 ($from_encoding) contains invalid encoding \"iso-8859-8-i\" in /var/www/html/custom_apps/mail/vendor/pear-pear.horde.org/Horde_Util/Horde/String.php:160` (both in the web service and in `cron.php` invocations).
I tried the patch in #5593 but that didn't help. Using the same approach (using `iconv` when `mb_convert_encoding` fails) in `vendor/pear-pear.horde.org/Horde_Util/Horde/String.php` fixed it for me. From what I see in the other issues, their error is also in `vendor/pear-pear.horde.org/Horde_Util/Horde/String.php` (I can't check the logs from Sentry as the link seems to be broken).

**Comment by ChristophWurst** [comment]
Not merged. Github didn't like my rebase and force push.

Path is

```patch
diff --git a/lib/Model/IMAPMessage.php b/lib/Model/IMAPMessage.php
index 95ac594c8..f043cb825 100644
--- a/lib/Model/IMAPMessage.php
+++ b/lib/Model/IMAPMessage.php
@@ -54,6 +54,7 @@ use OCP\AppFramework\Db\DoesNotExistException;
 use OCP\Files\File;
 use OCP\Files\SimpleFS\ISimpleFile;
 use ReturnTypeWillChange;
+use ValueError;
 use function fclose;
 use function in_array;
 use function mb_convert_encoding;
@@ -654,7 +655,11 @@ class IMAPMessage implements IMessage, JsonSerializable {
 		// data is utf-8 by default.
 		$charset = $p->getContentTypeParameter('charset');
 		if ($charset !== null && strtoupper($charset) !== 'UTF-8') {
-			$data = mb_convert_encoding($data, 'UTF-8', $charset);
+			try {
+				$data = mb_convert_encoding($data, 'UTF-8', $charset);
+			} catch (ValueError $exception) {
+				$data = iconv($charset, 'UTF-8', $data);
+			}
 		}
 		return $data;
 	}
```

**Comment by small1** [comment]
This gives nasty error 500 messages from all email from a supplier i have. For some reason they use windows-1257 in emails.  All i get is a loading body .

The try catch stuff did not fix it.

**Comment by brzd** [comment]
Would it be possible to show the mail source (as in 'view source' in mail app) instead of showing nothing, if the character encoding is not available? This way the mail would be at least to some extent readable instead of totally unavailable.

**Comment by Astinus-Eberhard** [comment]
Please can someone take care of this? For many people from central europe this is really annoying

**Comment by bmajik** [comment]
I'm getting the following in my logs:

ValueError
mb_convert_encoding(): Argument #3 ($from_encoding) contains invalid encoding "ks_c_5601-1987"

and


Exception
mb_convert_encoding(): Argument #3 ($from_encoding) contains invalid encoding "ks_c_5601-1987" in file '/var/www/html/custom_apps/mail/lib/IMAP/Charset/Converter.php' line 62

The raw message headers and bodies do indeed have ks_c_5601 chunks in them (I have a colleague working at a South Korean company using MS Outlook + Exchange servers)

Examples of that content encoding string showing up, all in the same message from him:

1. in MS proprietary anti-spam headers:

x-microsoft-antispam:
 BCL:0;ARA:13230040|1800799024|376014|366016|4053099003|8096899003|13003099007|4013099003|38070700018|7053199007;
x-microsoft-antispam-message-info:
 =?ks_c_5601-1987?B?bEM1OGFNQldxQTMrSGVOWENyelFVY3dJdGNKbzNGVTQ5aVFxKzNr?=
 =?ks_c_5601-1987?B?Ylg1cVQrRGdwTjJtV0RBalFCTjgzUG1Calk1MWRKZ21RYXkweEF2?=

2. as a charset encoding in a base64 content chunk:

--_000_BY5PR20MB3607BDB5C14EF9869DD50E9D9F812BY5PR20MB3607namp_
Content-Type: text/plain; charset="ks_c_5601-1987"
Content-Transfer-Encoding: base64

3. as a charset in a quoted-printable HTML content chunk:

--_000_BY5PR20MB3607BDB5C14EF9869DD50E9D9F812BY5PR20MB3607namp_
Content-Type: text/html; charset="ks_c_5601-1987"
Content-Transfer-Encoding: quoted-printable

<html xmlns:v=3D"urn:schemas-microsoft-com:vml" xmlns:o=3D"urn:schemas-micr=
osoft-com:office:office" xmlns:w=3D"urn:schemas-microsoft-com:office:word" =
xmlns:m=3D"http://schemas.microsoft.com/office/2004/12/omml" xmlns=3D"http:=
//www.w3.org/TR/REC-html40">
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dks_c_5601=
-1987">
<meta name=3D"Generator" content=3D"Microsoft Word 15 (filtered medium)">
<!--[if !mso]><style>v\:* {behavior:url(#default#VML);}

Note also inside of the quoted printable chunk, the HTML itself also embeds this encoding, in a URLescaped form...
