### ISSUE TITLE
Mails with i.e. greek characters not correctly displayed

### ISSUE THREAD

**Issue by sanchobear** [nextcloud/mail#2921]
### Expected behavior
When a mail in an other charset is received, it should be displayed correct

### Actual behavior
A mail written in i.e. greek characters is displayed unreadable.

### Mail app

**Mail app version:** 1.3.0

**Mailserver or service:** t-online.de

### Server configuration

**Operating system**: Ubuntu Server 18.05 LTS

**Web server:** nginx

**Database:** MariaDB

**PHP version:**  7.3

**Nextcloud Version:** 18.0.3

#### Client configuration
**Browser:** Chrome Version 80.0.3987.163 64 bit

**Operating system:** Win 10 (1909)

**Comment by ChristophWurst** [comment]
What part of the message? Could you post a screenshot?

**Comment by sanchobear** [comment]
See screenshot
![MailGr](https://user-images.githubusercontent.com/15321726/79487943-aa708b80-8021-11ea-9db0-6e74d131081d.jpg)

**Comment by ChristophWurst** [comment]
Looks like this could be an encoding issue. Is your php, webserver and nextcloud correctly set up? Check your admin settings UI for warnings or errors. Also please inspect the response from the HTTP request ending with `/html` that loads the message body. Check the headers for incorrect encoding.

**Comment by sanchobear** [comment]
Admin UI: No mail related errors or warnings
Chrome console: There is an error 404 with many mails concerning 'apps/mail/api/avatars/url/......' but no more
Headers: Encoding is utf-8
php: the subject is a h2 tag and displayed correctly

If I take the raw mail, the message is base64 and decode everything manually, the text inside span tags is displayed correctly in notepad++

**Comment by ChristophWurst** [comment]
> Also please inspect the response from the HTTP request ending with `/html` that loads the message body.

:point_up:

**Comment by sanchobear** [comment]
Anything more specific? Inspect for what?

Nextcloud mail content of <span> as text and in hex
ÎÏÎ´Î¹ÎºÏÏ Î&nbsp;Î»Î·ÏÏÎ¼Î®Ï
C38EC38FC38EC2B4C38EC2B9C38EC2BA
C38FC38F20C38E266E6273703BC38EC2
BBC38EC2B7C38FC38FC38EC2BCC38EC2
AEC38F

Manually decoded identical text
Κωδικός Πληρωμής
CE9ACF89CEB4CEB9CEBACF8CCF8220CE
A0CEBBCEB7CF81CF89CEBCCEAECF82

Seems as if greek gets converted to stange latin charset.

**Comment by ChristophWurst** [comment]
> Seems as if greek gets converted to strange latin charset.

Bingo. Now we just need to find out why.

**Comment by ChristophWurst** [comment]
Could you create a test account on that imap server and the nextcloud instance so I can inspect there?

**Comment by sanchobear** [comment]
Could send you the raw mail file - but as I can't sanitize it - not to public github

**Comment by sanchobear** [comment]
As I said, I could send the raw email as eml file, but not not public. I can't create an account on the IMAP server (btw it is t-online.de)! I could create an account on the nextcloud server. So this issue is definitly not closed.

**Comment by sanchobear** [comment]
? Something happening with this ?

**Comment by ChristophWurst** [comment]
no, we're busy finishing the v1.4 release

**Comment by nemphys** [comment]
Any news on this? It does not seem to have been fixed, yet the issue was closed.

**Comment by ChristophWurst** [comment]
@nemphys if possibly please provide us with a test email in the .eml or .mbox format

**Comment by miaulalala** [comment]
Possibly related to #5834

**Comment by miaulalala** [comment]
@nemphys still an issue? Just tested with the latest Mail and I get this:

![image](https://user-images.githubusercontent.com/7427347/218503783-8e43b41a-7f7f-44ab-9b5a-449e1e1b85af.png)


(Basic lorem ipsum text in greek character set)

Would apprechiate if you could test Mail another time :)

**Comment by nemphys** [comment]
@miaulalala sorry for the late reply.
Indeed the main message view seems to be OK now, but there is still an issue with the description/summary (not title) on the *message list view*; although the title appears properly, the text underneath it still shows up as gibberish.

**Comment by nemphys** [comment]
Since I am not familiar with the database structure, can you please provide the SQL query?

**Comment by miaulalala** [comment]
you need the id (last parameter when you have the message open) from the URL for this:

SELECT preview_text from oc_mail_messages where id = your_url_id;

**Comment by nemphys** [comment]
mysql> SELECT preview_text from oc_mail_messages where id = 15535;
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| preview_text                                                                                                                                                                                                                    |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ?????????4;???,? ????????? 0?????.??
|
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

Apparently it is written like that in the table row, it is not a matter of display encoding

**Comment by miaulalala** [comment]
that's what I suspected. Let me check if there's a way to reset your previews, I vaguely remember something.

**Comment by ChristophWurst** [comment]
Does it still happen?
