### ISSUE TITLE
IMAP errorMail server denied authentication

### ISSUE THREAD

**Issue by Bables55** [nextcloud/mail#3026]
### Actual behavior
The error has occurred frequently.

```
[mail] Error: OCA\Mail\Exception\ServiceException: IMAP errorMail server denied authentication. at <<closure>>

0. /MY-NEXTCLOUD/apps/mail/lib/BackgroundJob/SyncJob.php line 91
   OCA\Mail\IMAP\MailboxSync->sync(OCA\Mail\Account {}, true)
1. /MY-NEXTCLOUD/lib/public/BackgroundJob/Job.php line 79
   OCA\Mail\BackgroundJob\SyncJob->run({accountId: 9})
2. /MY-NEXTCLOUD/lib/public/BackgroundJob/TimedJob.php line 61
   OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
3. /MY-NEXTCLOUD/cron.php line 125
   OCP\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

[PHP] Error: Error while sending QUERY packet. PID=8627 at /MY-NEXTCLOUD/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php#88

[PHP] Error: Undefined offset: 3 at /MY-NEXTCLOUD/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php#3531

[PHP] Error: Error while sending QUERY packet. PID=8627 at /MY-NEXTCLOUD/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php#88

[mail] Error: OCA\Mail\Exception\ServiceException: Sync failed for 15:INBOX: An exception occurred while executing 'INSERT INTO `oc_mail_messages` (`uid`, `message_id`, `mailbox_id`, `subject`, `sent_at`, `flag_answered`, `flag_deleted`, `flag_draft`, `flag_flagged`, `flag_seen`, `flag_forwarded`, `flag_junk`, `flag_notjunk`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [29275, "<cd670ecb-8b65-4bed-f158-b4c79cafc593@courio-city.com>", 137, "[T :57159] \u6708\u66dc\u306eMLT", 1587109621, false, false, false, false, true, false, false, false]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '29275-137' for key 'UNIQ_706D6845539B060666EC35CC' at <<closure>>

0. /MY-NEXTCLOUD/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php line 107
   OCA\Mail\Service\Sync\ImapToDbSynchronizer->sync(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox {id: 137}, 42, null, false)
1. /MY-NEXTCLOUD/apps/mail/lib/BackgroundJob/SyncJob.php line 92
   OCA\Mail\Service\Sync\ImapToDbSynchronizer->syncAccount(OCA\Mail\Account {})
2. /MY-NEXTCLOUD/lib/public/BackgroundJob/Job.php line 79
   OCA\Mail\BackgroundJob\SyncJob->run({accountId: 15})
3. /MY-NEXTCLOUD/lib/public/BackgroundJob/TimedJob.php line 61
   OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
4. /MY-NEXTCLOUD/cron.php line 125
   OCP\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

[mail] Error: OCA\Mail\Exception\ServiceException: Sync failed for 8:INBOX: An exception occurred while executing 'INSERT INTO `oc_mail_messages` (`uid`, `message_id`, `mailbox_id`, `subject`, `sent_at`, `flag_answered`, `flag_deleted`, `flag_draft`, `flag_flagged`, `flag_seen`, `flag_forwarded`, `flag_junk`, `flag_notjunk`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [64267, "<address@domain.com>", 71, "[T :57460] mailtitle)", 1587602826, false, false, false, false, true, false, false, false]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '64267-71' for key 'UNIQ_706D6845539B060666EC35CC' at <<closure>>

0. /MY-NEXTCLOUD/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php line 107
   OCA\Mail\Service\Sync\ImapToDbSynchronizer->sync(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox {id: 71}, 42, null, false)
1. /MY-NEXTCLOUD/apps/mail/lib/BackgroundJob/SyncJob.php line 92
   OCA\Mail\Service\Sync\ImapToDbSynchronizer->syncAccount(OCA\Mail\Account {})
2. /MY-NEXTCLOUD/lib/public/BackgroundJob/Job.php line 79
   OCA\Mail\BackgroundJob\SyncJob->run({accountId: 8})
3. /MY-NEXTCLOUD/lib/public/BackgroundJob/TimedJob.php line 61
   OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
4. /MY-NEXTCLOUD/cron.php line 125
   OCP\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})
```
Most of the above errors appear as a set. 
There are multiple [mail] occurrences.

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.3.4
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Postfix

### Server configuration

**Operating system**: (e.g. Debian 8)
CentOS 7.7
**Web server:** (e.g. Apache, Nginx,...)
Nginx 1.16.1
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB 10.2.29
**PHP version:** (e.g. 7.0)
PHP 7.3.17
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
18.0.4

**Comment by ChristophWurst** [comment]
> The error has occurred frequently.

Like once an hour and in cron? This could just mean that one of the users' configured accounts has an invalid password.

**Comment by Bables55** [comment]
I'm now asking users to confirm their email accounts.

The following errors also appeared today.
```
[PHP] Error: Undefined offset: 2 at /MY-NEXTCLOUD/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php#3532
[PHP] Error: Undefined offset: 3 at /MY-NEXTCLOUD/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php#3531
```

**Comment by Bables55** [comment]
I've contacted most users and only one person has changed their password and that person's NC/Mail account has been fixed. But the same error occurred again.

**Comment by ChristophWurst** [comment]
> But the same error occurred again.

For a account that was checked by the user?

**Comment by Bables55** [comment]
I saw with my own eyes that the user was able to send and receive emails.

**Comment by ChristophWurst** [comment]
Do you have any other major issue on your instance? Because from the error trace it looks like your db is generally not configured correctly.

**Comment by stweil** [comment]
I see this error in a Nextcloud server log, too. It is caused by an old mail account of a user. That account was valid some time ago, but later removed on the IMAP server side. Now it is no longer possible to remove that old mail account because it is no longer visible for the user. As an admin I can still see the mail account in the database (table `oc_mail_accounts`).

**Comment by ChristophWurst** [comment]
> As an admin I can still see the mail account in the database (table `oc_mail_accounts`).

you can drop it there

**Comment by Bables55** [comment]
I can't identify the offending user by looking at the log.  What are some tips to identify a user?

**Comment by ChristophWurst** [comment]
what does the log say?

**Comment by ChristophWurst** [comment]
> Sync failed for 15:INBOX

Lines like these indicate it's about account with id 15

**Comment by stweil** [comment]
> I can't identify the offending user by looking at the log.

The log only contains the account id (a number). You'll have to look into the database to find the related user.

**Comment by Bables55** [comment]
`[mail] Fatal: OCA\Mail\Exception\ServiceException: IMAP errorMail server denied authentication. at <<closure>>
`
In this case, there is no number that would indicate an account ID.
```

[mail] Fatal: OCA\Mail\Exception\ServiceException: IMAP errorMail server denied authentication. at <<closure>>

0. /MY-NEXTCLOUD/nc/apps/mail/lib/Service/MailManager.php line 102
   OCA\Mail\IMAP\MailboxSync->sync(OCA\Mail\Account {})
1. /MY-NEXTCLOUD/nc/apps/mail/lib/Controller/PageController.php line 119
   OCA\Mail\Service\MailManager->getFolders(OCA\Mail\Account {})
2. /MY-NEXTCLOUD/nc/lib/private/AppFramework/Http/Dispatcher.php line 170
   OCA\Mail\Controller\PageController->index()
3. /MY-NEXTCLOUD/nc/lib/private/AppFramework/Http/Dispatcher.php line 100
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Controller\PageController {}, "index")
4. /MY-NEXTCLOUD/nc/lib/private/AppFramework/App.php line 137
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\PageController {}, "index")
5. /MY-NEXTCLOUD/nc/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Mail\\Controller\\PageController", "index", OC\AppFramework\ ... {}, {_route: "mail.page.index"})
6. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "mail.page.index"})
7. /MY-NEXTCLOUD/nc/lib/private/Route/Router.php line 297
   call_user_func(OC\AppFramework\ ... {}, {_route: "mail.page.index"})
8. /MY-NEXTCLOUD/nc/lib/base.php line 1007
   OC\Route\Router->match("/apps/mail/")
9. /MY-NEXTCLOUD/nc/index.php line 37
   OC::handleRequest()

GET /index.php/apps/mail/

```

**Comment by Bables55** [comment]
Thank you all.
I deleted my account and recreated my account within NC Mail. However, it still recurs even if Account ID is changed. And the error still occurs frequently. There seems to be no problem with the operation of the mail, but I am worried about the many errors. I've decided to give up using Mail.


Thanks,

**Comment by ChristophWurst** [comment]
Fair enough.

If you collaborated and helped debug your issue we could have improved the app for you and for other people.

**Comment by nicojx** [comment]
I have the same problem and happy to help if possible. I have set up NC using the snap package and am not an expert in databases etc., so would need some handholding. I have only one mail account set up, collecting mail using IMAP. I _think_ I tried to set up an account before but used the wrong password, and then deleted and started again.

Here's the log extract, the error occurs frequently, and not on the hour, or exactly every 20 or so minutes:


    OCA\Mail\Exception\ServiceException: Sync failed for 2:INBOX: Mail server denied authentication.

    /var/snap/nextcloud/28088/nextcloud/extra-apps/mail/lib/Service/Sync/SyncService.php - line 121:

    OCA\Mail\Service\Sync\ImapToDbSynchronizer->sync(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox { id: 48}, OC\AppFramew ... {}, 42, [ 18763,1876 ... "], false)

    /var/snap/nextcloud/28088/nextcloud/extra-apps/mail/lib/Controller/MailboxesController.php - line 161:

    OCA\Mail\Service\Sync\SyncService->syncMailbox(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox { id: 48}, 42, [ 2880,2879, ... "], true, null)

    /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 218:

    OCA\Mail\Controller\MailboxesController->sync(48, [ 2880,2879, ... "], false, null)

    /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 127:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "sync")

    /snap/nextcloud/28088/htdocs/lib/private/AppFramework/App.php - line 157:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "sync")

    /snap/nextcloud/28088/htdocs/lib/private/Route/Router.php - line 302:

    OC\AppFramework\App::main("OCA\\Mail\\ ... r", "sync", OC\AppFramew ... {}, { id: "48",_ ... "})

    /snap/nextcloud/28088/htdocs/lib/base.php - line 993:

    OC\Route\Router->match("/apps/mail/ ... c")

    /snap/nextcloud/28088/htdocs/index.php - line 37:

    OC::handleRequest()

     
    Caused by Horde_Imap_Client_Exception: Mail server denied authentication.

    /var/snap/nextcloud/28088/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 838:

    Horde_Imap_Client_Socket->_login("*** sensiti ... *")

    /var/snap/nextcloud/28088/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 1598:

    Horde_Imap_Client_Base->login("*** sensiti ... *")

    /var/snap/nextcloud/28088/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 4038:

    Horde_Imap_Client_Base->status(Horde_Imap_Client_Mailbox {}, 8713)

    /var/snap/nextcloud/28088/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 3632:

    Horde_Imap_Client_Base->_syncStatus(Horde_Imap_Client_Mailbox {})

    /var/snap/nextcloud/28088/nextcloud/extra-apps/mail/lib/IMAP/Sync/Synchronizer.php - line 109:

    Horde_Imap_Client_Base->sync(Horde_Imap_Client_Mailbox {}, "U18810,V1384857250,H36573", { criteria: 8})

    /var/snap/nextcloud/28088/nextcloud/extra-apps/mail/lib/IMAP/Sync/Synchronizer.php - line 65:

    OCA\Mail\IMAP\Sync\Synchronizer->getNewMessageUids(Horde_Imap_C ... e}, Horde_Imap_Client_Mailbox {}, OCA\Mail\IMAP\Sync\Request {})

    /var/snap/nextcloud/28088/nextcloud/extra-apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php - line 343:

    OCA\Mail\IMAP\Sync\Synchronizer->sync(Horde_Imap_C ... e}, OCA\Mail\IMAP\Sync\Request {}, 8)

    /var/snap/nextcloud/28088/nextcloud/extra-apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php - line 221:

    OCA\Mail\Service\Sync\ImapToDbSynchronizer->runPartialSync(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox { id: 48}, OC\AppFramew ... {}, 42, [ 18763,1876 ... "])

    /var/snap/nextcloud/28088/nextcloud/extra-apps/mail/lib/Service/Sync/SyncService.php - line 121:

    OCA\Mail\Service\Sync\ImapToDbSynchronizer->sync(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox { id: 48}, OC\AppFramew ... {}, 42, [ 18763,1876 ... "], false)

    /var/snap/nextcloud/28088/nextcloud/extra-apps/mail/lib/Controller/MailboxesController.php - line 161:

    OCA\Mail\Service\Sync\SyncService->syncMailbox(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox { id: 48}, 42, [ 2880,2879, ... "], true, null)

    /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 218:

    OCA\Mail\Controller\MailboxesController->sync(48, [ 2880,2879, ... "], false, null)

    /snap/nextcloud/28088/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 127:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "sync")

    /snap/nextcloud/28088/htdocs/lib/private/AppFramework/App.php - line 157:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "sync")

    /snap/nextcloud/28088/htdocs/lib/private/Route/Router.php - line 302:

    OC\AppFramework\App::main("OCA\\Mail\\ ... r", "sync", OC\AppFramew ... {}, { id: "48",_ ... "})

    /snap/nextcloud/28088/htdocs/lib/base.php - line 993:

    OC\Route\Router->match("/apps/mail/ ... c")

    /snap/nextcloud/28088/htdocs/index.php - line 37:

    OC::handleRequest()`

**Comment by ChristophWurst** [comment]
> Here's the log extract, the error occurs frequently, and not on the hour, or exactly every 20 or so minutes:

Please copy the raw log message (the one in json format) and open a new ticket. Thanks :)
