### ISSUE TITLE
Sender's name (From:) shown as ???????? (UTF-8 issue)

### ISSUE THREAD

**Issue by Master0ne** [nextcloud/mail#3210]
### Expected behavior
The sender's name (**From:**) should be shown correctly. In the example from the attached screenshot that is **vermaden**

Message source shows it as  
**=?UTF-8?B?8J2an/Cdmo7wnZqb8J2alvCdmorwnZqN8J2ajvCdmpc=?=**

### Actual behavior
The sender's name (**From:**) is shown as **????????** instead:

![mail_screenshot](https://user-images.githubusercontent.com/8912853/83936124-9f83dd00-a7c0-11ea-9aa9-dab1317eb4e4.png)

### Mail app

**Mail app version:** 1.3.5
**Mailserver or service:** Hetzner

### Server configuration

**Operating system**: Debian
**Web server:** Apache 2.4.38
**Database:** MySQL
**PHP version:** 7.4.6
**Nextcloud Version:** 18.0.5

#### Client configuration

**Browser:** Firefox 77.0.1 / Chromium 83.0.4103.61
**Operating system:** Arch Linux

**Comment by ChristophWurst** [comment]
> **Database:** MySQL

utf8 issues with mysql can be almost always solved by following https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html closely. Please read this carefully and adjust your database.

**Comment by Master0ne** [comment]
I guess it kind of worked, I followed all the shown steps for MySQL 8.0 or later precisely (including the database repair with `php occ maintenance:repair`), and the latest mailing from *vermaden* (from 2 days ago) is now shown correctly, but older mails (from 9 days ago and older) are still shown with the question marks as sender's name:

![screenshot](https://user-images.githubusercontent.com/8912853/84246462-f2ce9600-ab06-11ea-99c9-8b757ab9a47e.png)

Is there something else to do to make it all show up correctly?

**Comment by ChristophWurst** [comment]
> I guess it kind of worked, I followed all the shown steps for MySQL 8.0 or later precisely (including the database repair with `php occ maintenance:repair`), and the latest mailing from _vermaden_ (from 2 days ago) is now shown correctly, but older mails (from 9 days ago and older) are still shown with the question marks as sender's name:

That is because the old ones were inserted incorrectly and we otherwise assume subjects to be immutable, so it's not subject to updates.

You can [enable debug mode](https://docs.nextcloud.com/server/stable/developer_manual/general/devenv.html#enabling-debug-mode) and reload the page, then in the mailbox ... menu in the navigation a new entry will show up that allows you to clear the cache. Disable debug mode afterwards again.
