### ISSUE TITLE
S/Mime certificate does not encrypte/sign messages

### ISSUE THREAD

**Issue by DanialSh** [nextcloud/mail#8552]
### Steps to reproduce

1. I imported my S/Mime certificate to NextCloud Mail using the certificate file and password.
2. I tried sending an email from the email account corresponding to the certificate
3. I confirmed the sent email was not encrypted/signed by S/Mime. 

This is not an issue when I use the same certificate file/password with Thunderbird to have my sent emails signed/encrypted.

### Expected behavior

I expect my imported S/Mime certificate to be used with the corresponding email address.

### Actual behavior

Imported S/Mime is used to encrypt/sign my outgoing emails. 

### Mail app version

3.2.1

### Mailserver or service

Personal Email Server

### Operating system

Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MySQL

### Additional info

I tried to update the smime_certificate_id.oc_mail_accounts manually. but it still didn't work. It was originally set to null.

```
mysql> select id, email_address from oc_mail_smime_certificates;
+----+------------------+
| id | email_address    |
+----+------------------+
|  2 | <my_email> |
+----+------------------+
1 row in set (0.00 sec)

mysql> select smime_certificate_id, email from oc_mail_accounts where id = 15;
+----------------------+------------------+
| smime_certificate_id | email            |
+----------------------+------------------+
|                    2 | <my_email> |
+----------------------+------------------+
1 row in set (0.00 sec)
```

_No response_

**Comment by joshuniverse** [comment]
Second, can confirm the emails are not signed.

**Comment by ChristophWurst** [comment]
@joshuniverse add your :+1: to https://github.com/nextcloud/mail/issues/8552#issue-1759634270 please

**Comment by alexh-swdev** [comment]
@DanialSh can you assign the certificate to its alias? I cannot even do that, I can only upload it.

**Comment by gvansanden** [comment]
> @DanialSh can you assign the certificate to its alias? I cannot even do that, I can only upload it.

I fixed that in the database directly....

**Comment by eazel7** [comment]
> > @DanialSh can you assign the certificate to its alias? I cannot even do that, I can only upload it.
> 
> I fixed that in the database directly....

how did you do that? I find myself in the same situation

**Comment by wvogel** [comment]
Did the same as @gvansanden described: Fixed the database with
`update oc_mail_accounts set smime_certificate_id = XXX where id = ZZZ;`
And now when i klick the 3 dots next to "send" i get a checkbox "_sign message with S/MIME_" that actually does it's job and signs the message.

**Comment by 3EE45A47** [comment]
Thank you, this helped me a lot - encryption/signature works, now :-)
Nevertheless the UI (Mail v3.5.5@NC26.0.11) seems still not to be able to pick it up to handle it, then.

**Comment by st3iny** [comment]
The certificate is omitted from the select if the signing CA is not imported into your Nextcloud server. On the other hand, I can see that this can be confusing to users. 

You have to make sure to run `occ security:certificates:import $PWD/ca.crt` or similar if you are using a custom CA to sign your S/MIME certs.

Maybe we should remove the validity check when selecting certificates and instead show a warning if an untrusted certificate is selected.

Signing and encrypting works even with untrusted certificates, hence the suggested sql query workaround is working.

**Comment by alexh-swdev** [comment]
Well... "confusing" is nice said. What about a message?
Btw my non-working cert is from GlobalSign, so imho not a "custom CA".....

**Comment by st3iny** [comment]
Nevertheless, please try to import it explicitly into your Nextcloud server as it might be missing from the bundle. It kind of depends on the CA bundle your distribution ships as well (which might be horribly outdated in some cases).

**Comment by ChristophWurst** [comment]
> .. i would appreciate, if the "green-lock-message" would mention a more specific status for each, encryption as well as signature. Currently for "just signed" eMails an appropriate info is shown - for "encrypted" and "encrypted and signed" eMails the same message is used for both which does not specify the signature status. Maybe some certificate-details can be also included here?

Please use https://github.com/nextcloud/mail/issues/new?assignees=&labels=enhancement%2C0.+to+triage&projects=&template=feature_request.yml
