### ISSUE TITLE
Mail-App Advanced Search Bug

### ISSUE THREAD

**Issue by AlexanderZuehr** [nextcloud/mail#8954]
### Steps to reproduce

Hey if I try to use the mail-app advanced search and filter for a mail-address with the "From" field, i see all mails which are matching the "From" field but also I see all mails that are matching the "To" Field.

Normally if I want to filter "From" the mail-app should only show all mails which are matching the "From" field.

<img width="602" alt="Bildschirmfoto 2023-10-11 um 11 42 19" src="https://github.com/nextcloud/mail/assets/76497172/ffe1327c-4b89-43b7-ba30-a120f89ef226">

### Mail app version

3.4.0

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

MariaDB

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/mail/pull/8953, too.

**Comment by AlexanderZuehr** [comment]
After applying this patch all the other fields are also mixed up. For example if I filter for "CC" and my mail-address I also see mails where I am listed in "To" or "From".

**Comment by ChristophWurst** [comment]
But the patch fixes the database error, no?

The sematic error can be checked as well. I don't see an obvious flaw with the query.

**Comment by AlexanderZuehr** [comment]
The patch fixed the error shown which I had in #8952 
But this bug is still there.

As you can see in the attached pictures I am now able to filter for "CC" with my mail-address, but I do also see mail where my mail-address is in "From" oder in "To", so this is now the same problem I described at the start of this ticket.

<img width="466" alt="Bildschirmfoto 2023-10-11 um 13 51 18" src="https://github.com/nextcloud/mail/assets/76497172/facbf863-94db-4b05-a18a-c28dc521ddb7">
<img width="240" alt="Bildschirmfoto 2023-10-11 um 13 51 07" src="https://github.com/nextcloud/mail/assets/76497172/19b9f2ba-0e1b-4d94-a711-adb5a65aede5">
<img width="603" alt="Bildschirmfoto 2023-10-11 um 13 50 55" src="https://github.com/nextcloud/mail/assets/76497172/13fe9def-ec47-437d-9dd7-c0723739b02c">

**Comment by ChristophWurst** [comment]
> I am now able to filter for "CC" with my mail-address, but I do also see mail where my mail-address is in "From" oder in "To", so this is now the same problem I described at the start of this ticket.
> But now this problem is not only occurring if I filter "From" but is is occurring for "From", "To", "Cc" Bcc".

Excellent observation. Please see https://github.com/nextcloud/mail/pull/8959.

**Comment by AlexanderZuehr** [comment]
#8959 solved the Problem completely. Thank you very much.

**Comment by ChristophWurst** [comment]
Awesome
